In [2]:
import pandas as pd
mapping = pd.read_excel('/mnt/SSD5/yipeng/BIDS_combined/combined/Draft_metadata_all_subjects.xlsx', sheet_name='Combined')

In [3]:
mapping = mapping[['Database No.', 'Paper No.']]

In [4]:
mapping['Paper No.'] = mapping['Paper No.'].str.replace('_', '')

In [6]:
import os
import numpy as np
folder1 = "/mnt/SSD5/yipeng/VAE/data_new/"
folder2 = "/mnt/SSD5/yipeng/VAE/data/"
dataset = "detroit"
pt_names1 = os.listdir(os.path.join(folder1, dataset))
pt_names2 = os.listdir(os.path.join(folder2, dataset))
for i in range(len(pt_names1)):
    pt_name1 = pt_names1[i]
    print(pt_name1.split("-")[1].replace("_",""))
    pt_name2 = mapping.loc[mapping['Paper No.'] == pt_name1.split("-")[1], 'Database No.'].values[0]
    feature_fn1 = os.path.join(folder1, dataset, pt_name1, "feature.npz")
    feature_fn2 = os.path.join(folder2, dataset, pt_name2, "feature.npz")
    
    feature1 = np.load(feature_fn1)["feature"]
    feature2 = np.load(feature_fn2)["feature"]
    # feature 1 and feature 2 are both (n, 64, 64)
    # I want to calculate if they are the same
    # lets output one value for each feature
    print(np.mean(np.abs(feature1 - feature2)))


UCLA31
0.0
UCLA28
0.0
UCLA03
0.0
UCLA41
0.0
UCLA27
0.0
UCLA15
0.0
UCLA01
0.0
UCLA05
0.0
UCLA06
0.0
UCLA23
0.0
UCLA24
0.0
UCLA34
0.0
UCLA19
0.0
UCLA13
0.0
UCLA30
0.0
UCLA12
0.0
UCLA09
0.0
UCLA48
0.0
UCLA07
0.0
UCLA26
0.0
UCLA04
0.0
UCLA38
0.0
UCLA10
0.0
UCLA20
0.0
UCLA21
0.0
UCLA02
0.0
UCLA14
0.0
UCLA33
0.0
UCLA16
0.0
UCLA08
0.0
UCLA17
0.0


In [5]:
import os
import numpy as np
folder1 = "/mnt/SSD5/yipeng/VAE/data_new/"
folder2 = "/mnt/SSD5/yipeng/VAE/data/"
dataset = "seeg"
pt_names1 = os.listdir(os.path.join(folder1, dataset))
pt_names2 = os.listdir(os.path.join(folder2, dataset))
for i in range(len(pt_names1)):
    pt_name1 = pt_names1[i]
    print(pt_name1.split("-")[1].replace("_",""))
    pt_name2 = mapping.loc[mapping['Paper No.'] == pt_name1.split("-")[1], 'Database No.'].values[0]
    feature_fn1 = os.path.join(folder1, dataset, pt_name1, "feature.npz")
    feature_fn2 = os.path.join(folder2, dataset, pt_name2, "feature.npz")
    
    feature1 = np.load(feature_fn1)["feature"]
    feature2 = np.load(feature_fn2)["feature"]
    # feature 1 and feature 2 are both (n, 64, 64)
    # I want to calculate if they are the same
    # lets output one value for each feature
    print(np.sum(np.abs(feature1 - feature2)))

UCLA18
0.0
UCLA36
0.0
UCLA44
0.0
UCLA49
0.0
UCLA11
0.0
UCLA39
0.0
UCLA25
0.0
UCLA32
0.0
UCLA45
0.0
UCLA50
0.0
UCLA35
0.0
UCLA40
0.0
UCLA43
0.0
UCLA42
0.0
UCLA47
0.0
UCLA46
0.0
UCLA29
0.0
UCLA37
0.0


In [2]:
import mne

In [34]:
fn = "/mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_A_ave.edf"
#raw1 = mne.io.read_raw_edf(fn, preload=True)
fn2 = "/mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_B_ave.edf"
#raw2 = mne.io.read_raw_edf(fn2, preload=True)

import mne
import numpy as np

def merge_edf(file1, file2, output_file):
    # Read the two EDF files
    raw1 = mne.io.read_raw_edf(file1, preload=True)
    raw2 = mne.io.read_raw_edf(file2, preload=True)
    raw1.add_channels([raw2])

    # Save the combined raw data to a new EDF file
    raw1.export(output_file, fmt='edf', overwrite=True)

# Example usage
merge_edf(fn, fn2, 'merged.edf')



Extracting EDF parameters from /mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_A_ave.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 11451999  =      0.000 ...  5725.999 secs...
Extracting EDF parameters from /mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_B_ave.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 11451999  =      0.000 ...  5725.999 secs...
Overwriting existing file.


In [16]:
a[0]

array([ 0.00013255,  0.0001842 ,  0.00022797, ..., -0.03432889,
       -0.03433991, -0.03432889])

In [17]:
raw.info['ch_names']

['G1',
 'G2',
 'G3',
 'G4',
 'G5',
 'G6',
 'G7',
 'G8',
 'G9',
 'G10',
 'G11',
 'G12',
 'G13',
 'G15',
 'G16',
 'G17',
 'G18',
 'G19',
 'G21',
 'G22',
 'G23',
 'G24',
 'G26',
 'G27',
 'G28',
 'G31',
 'G32',
 'G33',
 'G34',
 'G37',
 'G38',
 'G39',
 'G40',
 'G41',
 'G42',
 'G44',
 'G47',
 'G49',
 'G50',
 'G51',
 'G52',
 'G53',
 'G54',
 'G55',
 'G56',
 'G57',
 'G58',
 'G59',
 'G60',
 'G61',
 'G62',
 'G63',
 'G64']

In [10]:
import mne
fn1 = "/mnt/SSD5/yipeng/BIDS_combined/combined/sub-UCLA30/ses-01/ieeg/sub-UCLA30_ses-01_task-sleep_ieeg.edf"
raw1 = mne.io.read_raw_edf(fn1, preload=True)
print(raw1.info['ch_names'])
a = raw1.get_data()
a[-1]

Extracting EDF parameters from /mnt/SSD5/yipeng/BIDS_combined/combined/sub-UCLA30/ses-01/ieeg/sub-UCLA30_ses-01_task-sleep_ieeg.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 11451999  =      0.000 ...  5725.999 secs...
['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', 'G13', 'G15', 'G16', 'G17', 'G18', 'G19', 'G21', 'G22', 'G23', 'G24', 'G26', 'G27', 'G28', 'G31', 'G32', 'G33', 'G34', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42', 'G44', 'G47', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54', 'G55', 'G56', 'G57', 'G58', 'G59', 'G60', 'G61', 'G62', 'G63', 'G64', 'DAM1', 'DAM2', 'DAM3', 'DAM4', 'DAM5', 'DAM6', 'DM1', 'DM2', 'DM3', 'DM4', 'DM5', 'DM6', 'DP1', 'DP2', 'DP3', 'DP4', 'DP5', 'DP6', 'DL1', 'DL2', 'DL3', 'DL4', 'DL5', 'DL6', 'ST1', 'ST2', 'ST3', 'ST4', 'ST5', 'ST6', 'ST7', 'ST8', 'SPO1', 'SPO2', 'SPO3', 'SPO4', 'SPO5', 'SPO6', 'SPO7', 'SPO8']


array([ 0.00083879,  0.00081109,  0.00077415, ..., -0.02163528,
       -0.02163528, -0.02163528])

In [12]:
fn2= "/mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_B_ave.edf"
raw2 = mne.io.read_raw_edf(fn2, preload=True)
print(raw2.info['ch_names'])
b = raw2.get_data()
b[-1]

Extracting EDF parameters from /mnt/SSD2/Atsuro_sz_data/Ave_new/AN2019_B_ave.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 11451999  =      0.000 ...  5725.999 secs...
['DAM1', 'DAM2', 'DAM3', 'DAM4', 'DAM5', 'DAM6', 'DM1', 'DM2', 'DM3', 'DM4', 'DM5', 'DM6', 'DP1', 'DP2', 'DP3', 'DP4', 'DP5', 'DP6', 'DL1', 'DL2', 'DL3', 'DL4', 'DL5', 'DL6', 'ST1', 'ST2', 'ST3', 'ST4', 'ST5', 'ST6', 'ST7', 'ST8', 'SPO1', 'SPO2', 'SPO3', 'SPO4', 'SPO5', 'SPO6', 'SPO7', 'SPO8']


array([ 0.00083954,  0.00081115,  0.00077483, ..., -0.0216356 ,
       -0.0216356 , -0.0216356 ])

In [37]:
#raw channel
